### ISSUE TITLE
relative imports doesn't work for python 2.4

### ISSUE THREAD

**Issue by eamonnkenny** [copitux/python-github3#31]
from .keys import keys

doesn't seem to work for pygithub3/service/user/**init**.py

this affects many other files also.

**Comment by eamonnkenny** [comment]
Example of problem

Traceback (most recent call last):
  File "./github-BugConversion.py", line 99, in ?
    main(sys.argv)
  File "./github-BugConversion.py", line 93, in main
    gitHubXMLobject = GitHubToXML( executableFullPath )
  File "./github-BugConversion.py", line 19, in **init**
    self.github = Github()
  File "./python-github3-master/pygithub3/github.py", line 17, in **init**
    from pygithub3.services.users import User
  File "./python-github3-master/pygithub3/services/users/**init**.py", line 5
    from .keys import Keys

Where

# python

> > import sys
> > 
> > > sys.version_info
> > > (2, 4, 3, 'final', 0)
